_wandb:
    value:
        cli_version: 0.25.0
        e:
            33od3yt49mvf1wniudbqtb8ksq3u2dpl:
                args:
                    - config/train_shakespeare_char.py
                    - --device=xpu
                    - --compile=False
                    - --wandb_log=True
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "39052693504"
                        used: "33142812672"
                email: s2818750@ed.ac.uk
                executable: /home/linux/env/rscam/bin/python
                git:
                    commit: eff80ec4060cebaa18fb69cb54b115d65fa45528
                    remote: https://github.com/ardenpalme/nanoGPT.git
                host: linux
                memory:
                    total: "66823376896"
                os: Linux-6.18.13-arch1-1-x86_64-with-glibc2.43
                program: /home/linux/Documents/UoE/Research Skills for CAM/Group Project/nanoGPT/train.py
                python: CPython 3.12.12
                root: /home/linux/Documents/UoE/Research Skills for CAM/Group Project/nanoGPT
                startedAt: "2026-03-05T14:18:51.983188Z"
                writerId: 33od3yt49mvf1wniudbqtb8ksq3u2dpl
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 256
compile:
    value: false
dataset:
    value: shakespeare_char
decay_lr:
    value: true
device:
    value: xpu
dropout:
    value: 0.2
dtype:
    value: float16
eval_interval:
    value: 250
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 0.0001
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
out_dir:
    value: out-shakespeare-char
wandb_log:
    value: true
wandb_project:
    value: shakespeare-char
wandb_run_name:
    value: mini-gpt
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
